import Image from "next/image";
import CustomizedMenus from "./CustomizedMenus";

//metadata
export const metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function Home() {
    return ( 
      <div>
        Welcome 
      </div>
    );
}